### ISSUE TITLE
Double ?query parameters when using awesomebar keyword search

### ISSUE THREAD

**Issue by chrismore** [mozilla-iam/dino-park-front-end#398]
**Describe the bug**

When using a keyword bookmark for the new directory's search box, a double query parameter is returned in the query thus invalidating the results.

**To Reproduce**

1. Go to https://people.mozilla.org/
2. Right click on search box
3. Add keyword "pb" to search (example)
4. Go to awesomebar and type in "pb cmore"

**Expected behavior**

Query returned as:

https://people.mozilla.org/s?query=cmore&who=staff

Since there are two query parameters, their results are concatenated with a comma, thus, the search is returned as ",cmore".

** Actual Results**

https://people.mozilla.org/s?query&query=cmore&who=staff

Two query 'query' parameters.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Firefox 67

**Comment by viorelaioia** [comment]
This is fixed in people.mozilla.org. @chrismore , can you confirm it works for you as well? Thanks!

**Comment by chrismore** [comment]
@viorelaioia r+ fixed! looks good now. thanks!
