### ISSUE TITLE
Bevel on large buttons

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#42]
Bevel on large buttons should be radius 23. See attached image.

<img width="220" alt="screen shot 2018-10-12 at 9 05 44 pm" src="https://user-images.githubusercontent.com/43189936/46901129-a11dc600-ce62-11e8-8abe-a130abdce519.png">

**Comment by hidde** [comment]
Do you mean the radius of the border?
