### ISSUE TITLE
top nav profile pic has artifacts on the top and bottom

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#43]
top nav profile pic has artifacts on the top and bottom. unsure if this part of the image or placement? See attached image.

<img width="152" alt="screen shot 2018-10-12 at 9 15 44 pm" src="https://user-images.githubusercontent.com/43189936/46901193-205fc980-ce64-11e8-96e8-4febd49f989c.png">

**Comment by hidde** [comment]
This is part of the image and therefore a content issue. Will be more realistic once we display real photos from the system.

Closing this issue as it is not a front-end issue.
