### ISSUE TITLE
[Org chart] Expand/Collapse fades - make instant transition

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#49]
Currently when you expand or collapse the orgchart there is a 1-2 second fade. Make this transition instant with no fade so interaction feels more responsive. See attached zip file with video inside.

[fade_mouseover.zip](https://github.com/mozilla-iam/dino-park-front-end/files/2475066/fade_mouseover.zip)

**Comment by hidde** [comment]
Removed the transition.
