### ISSUE TITLE
Design should profile card get this thin?

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#51]
<img width="808" alt="screen shot 2018-10-12 at 9 42 03 pm" src="https://user-images.githubusercontent.com/43189936/46901390-bea15e80-ce67-11e8-8c1f-3305e5c0459c.png">

**Comment by hidde** [comment]
Closing this, as it is the same issue as in #52, let's make a choice there.

**Comment by rfirebaugh** [comment]
Notes:
-fix the buttons to look as zeplin
-stack contact me and view full profile buttons
