### ISSUE TITLE
[Profile preview] Decide on breakpoint between small and large screen version

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#52]
<img width="777" alt="screen shot 2018-10-12 at 9 43 08 pm" src="https://user-images.githubusercontent.com/43189936/46901394-ded11d80-ce67-11e8-9b5f-d8145392722e.png">

**Comment by hidde** [comment]
You can pick at which screen width we switch from this modal preview to the regular sticky cards. Note that this should be a width on which the org chart and preview comfortably fit next to each other.
