### ISSUE TITLE
[Profile preview] Mobile close button does not have correct formatting

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#53]
mobile web close button does not have correct formatting see attached image

<img width="94" alt="screen shot 2018-10-12 at 9 43 49 pm" src="https://user-images.githubusercontent.com/43189936/46901403-06c08100-ce68-11e8-93e1-eafe1992da8d.png">

**Comment by hidde** [comment]
What does this mean?
