### ISSUE TITLE
Profile card images not all uniformed

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#54]
Profile card images not all uniformed. Unsure if this is with the actual image or code?
See attached images.

<img width="276" alt="screen shot 2018-10-12 at 9 46 31 pm" src="https://user-images.githubusercontent.com/43189936/46901423-6585fa80-ce68-11e8-84e4-89a03c1235a2.png">
<img width="229" alt="screen shot 2018-10-12 at 9 46 19 pm" src="https://user-images.githubusercontent.com/43189936/46901424-6585fa80-ce68-11e8-84d6-4a65e0eaeb0d.png">
<img width="268" alt="screen shot 2018-10-12 at 9 46 04 pm" src="https://user-images.githubusercontent.com/43189936/46901425-6585fa80-ce68-11e8-8fbe-29cc91228cc2.png">
<img width="246" alt="screen shot 2018-10-12 at 9 45 38 pm" src="https://user-images.githubusercontent.com/43189936/46901426-6585fa80-ce68-11e8-9cec-677864fa77d4.png">

**Comment by hidde** [comment]
This is a content issue. We use a random image generator, so the images you see here are of random sizes. With real data we will have correctly scaled and sized images.

Closing this issue for now as there is nothing we can do about it from the front-end.
