### ISSUE TITLE
[Profile preview] ‘Mozillian for 4 years’ tooltip does not line up as intended

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#55]
# mozillian years tooltip does not line up as intended see attached image.

<img width="261" alt="screen shot 2018-10-12 at 9 47 46 pm" src="https://user-images.githubusercontent.com/43189936/46901438-90704e80-ce68-11e8-8430-f30d27abae6a.png">

**Comment by hidde** [comment]
As I understand, we are looking at redesigning this feature and its redesign may not use the hover pattern, so I am currently pausing development on it.
