### ISSUE TITLE
Safari v12 not able to reduce width any smaller 

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#59]
Safari v12 not able to reduce width any smaller. Unsure if this a limitation of the software or programming for the page itself. See side by side comparison with firefox.

<img width="882" alt="screen shot 2018-10-12 at 9 58 02 pm" src="https://user-images.githubusercontent.com/43189936/46901497-222c8b80-ce6a-11e8-8a23-6b401f86d922.png">
<img width="507" alt="screen shot 2018-10-12 at 9 57 52 pm" src="https://user-images.githubusercontent.com/43189936/46901498-222c8b80-ce6a-11e8-809a-ac6abf3f26e2.png">
<img width="516" alt="screen shot 2018-10-12 at 9 57 47 pm" src="https://user-images.githubusercontent.com/43189936/46901499-222c8b80-ce6a-11e8-9097-33f2e1af1b61.png">

**Comment by hidde** [comment]
This varies per browser. Closing this issue as we have no away to influence this and generally very few people would look at this width on a desktop browser.
