### ISSUE TITLE
[Org chart] Allow list to be collapsed to a specific person

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/dino-park-front-end#63]
We want it to be possible to link to a specific person in the org chart. In that route, we want the org chart to be collapsed all the way to that person, so that you can see the person's manager/managees.

Specifics:
* org chart collapses to specific person
* scroll position is set so that blue background of highlighted person starts where top of profile preview card starts

┆Attachments: <a href="https:&#x2F;&#x2F;mozilla-pmo.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10227&#x2F;image-20181122-114137.png">image-20181122-114137.png</a>

**Comment by hidde** [comment]
@fiji-flo I believe you are working on something to allow for this, assigning to you

**Comment by fiji-flo** [comment]
this should be addressed in #90

**Comment by mbransn** [comment]
@hidde I agree with the above for Desktop, but for mobile I don't know that the profile card should be shown by default. This interrupts the experience of viewing the individual in the org chart when utilizing smaller screens.

**Comment by hidde** [comment]
We're building one website that works across different screen sizes, having slight differences based on viewport can be done, but this is changing the functionality quite a bit.

The current logic is: _person is selected_ means _person is previewed_.  What we have is a link to a page where a person is selected. On mobile, selected means shown in a modal overlay instead of just shown. This is not ideal, as it means blocking scrolling and focus only on small screens, but we made it work.

To make what ‘person is selected’ means different depending on viewports is a rabbithole I'd rather not go down. What, for example, if someone copypastes the URL they're looking at on their phone, onto their desktop, or vice versa? What if someone sets their font size to `400%` on desktop, because they can't see well?  What if they turn their device and that turning causes it to be classified as a different type of viewport?

Proposal: keep it as is.
