### ISSUE TITLE
Redirect from mozillians goes to /u/ instead of /p/

### ISSUE THREAD

**Issue by chutten** [mozilla-iam/dino-park-front-end#636]
**Describe the bug**
An old mozillians link like https://mozillians.org/u/chutten/ does successfully redirect to dinopark, but not quite correctly. It sends you to https://people.mozilla.org/u/chutten/ (which doesn't exist) instead of https://people.mozilla.org/p/chutten/ (which does)

**To Reproduce**
1. Go to  https://mozillians.org/u/chutten/ 

**Expected behavior**
To be redirected seamlessly to https://people.mozilla.org/p/chutten/

**Desktop (please complete the following information):**
 - OS: At least Linux and Windows (probably all)
 - Browser Firefox (probably all)
 - Version Nightly 2021-02-02

**Comment by floatingatoll** [comment]
The old mozillians.org domain is handled by the redirect service now, so I've opened this internally as SE-1960 for my team. Closing here to avoid duplication.
