### ISSUE TITLE
desktop user menu does not match zeplin design

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#65]

**Comment by hidde** [comment]
As expressed when we met: I have a strong preference for having the X / close button everywhere. 

There will be a close button in the page as it exists on small screens, screen readers will also be able to use it, it feels unfair to hide it from sighted desktop users only.

**Comment by mbransn** [comment]
@hidde this is coming from me and I'm willing to let go of it. Updating to read "utilize `x` icon for user menu close universally".

Note that this shift of image to the left on desktop will require a slightly wider user menu than is currently [designed](https://app.zeplin.io/project/5b61ec0e22302659883e6834/screen/5bbae6cc0343415fc7f50991).

**Comment by rfirebaugh** [comment]
Mimic desktop experience for how user menu is closed on mobile web. See updated zeplin file.
